[package]
name = "stereogif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
show-image = "0.10.1"
jpeg-decoder = "0.2.2"